#!/command/with-contenv sh

# Optional LemonLDAP::NG Manager API, served on manager-api.$SSODOMAIN
# See README.md for MANAGER_API* variables

CONF=/etc/lemonldap-ng/manager-api-nginx.conf
PSGI=/etc/lemonldap-ng/manager-api.psgi
HTPASSWD=/etc/lemonldap-ng/manager-api.htpasswd
TEMPLATE=/usr/share/docker-llng/manager-api-nginx.conf

set -e

die() {
	rm -f $CONF.new $PSGI
	echo "Manager API: $*" >&2
	exit 1
}

# Start from a disabled API: any error below leaves it disabled
echo "# Manager API disabled (set MANAGER_API=yes to enable it)" >$CONF
rm -f $PSGI $HTPASSWD

if test "$MANAGER_API" != "yes"; then
	exit 0
fi

case "$MANAGER_API_READONLY" in
	""|yes|no) ;;
	*) die "MANAGER_API_READONLY must be 'yes' or 'no'" ;;
esac

# Listening port: by default, the manager-api.$SSODOMAIN virtual host on the
# main port. With MANAGER_API_PORT, the API is alone on its own port, so it
# answers whatever the Host header (to be reached through a reverse proxy
# that routes /api/ to this port for example)
LISTEN=80
if test "$MANAGER_API_PORT" != ""; then
	case "$MANAGER_API_PORT" in
		*[!0-9]*) die "MANAGER_API_PORT must be a port number" ;;
	esac
	if test "$MANAGER_API_PORT" -lt 1 -o "$MANAGER_API_PORT" -gt 65535 \
		-o "$MANAGER_API_PORT" -eq 80 -o "$MANAGER_API_PORT" -eq 443; then
		die "MANAGER_API_PORT must be a free port number (not 80 or 443)"
	fi
	LISTEN=$MANAGER_API_PORT
elif test "$TLS_CERT_FILE"; then
	LISTEN=443
fi
if test "$TLS_CERT_FILE"; then
	LISTEN="$LISTEN ssl"
fi
export LISTEN

# Normalize lists (blank values are considered as empty)
for v in MANAGER_API_ALLOW MANAGER_API_OAUTH2_CLIENTS; do
	eval "$v=\$(perl -e 'print join \" \", grep { length } split /[,\\s]+/, \$ENV{$v}')"
	export $v
done

if test "$MANAGER_API_ALLOW" = "" -a "$MANAGER_API_AUTHBASIC" = "" -a "$MANAGER_API_OAUTH2_CLIENTS" = ""; then
	die "refusing to expose an unprotected API: set MANAGER_API_OAUTH2_CLIENTS, MANAGER_API_ALLOW and/or MANAGER_API_AUTHBASIC"
fi

if test "$MANAGER_API_AUTHBASIC" != ""; then
	if test "$MANAGER_API_OAUTH2_CLIENTS" != ""; then
		die "MANAGER_API_AUTHBASIC and MANAGER_API_OAUTH2_CLIENTS can't be used together (both use Authorization header)"
	fi
	AUTHUSER=${MANAGER_API_AUTHBASIC%%:*}
	AUTHPWD=${MANAGER_API_AUTHBASIC#*:}
	if test "$MANAGER_API_AUTHBASIC" = "$AUTHUSER" -o "$AUTHPWD" = "" -o "$AUTHUSER" = ""; then
		die "malformed MANAGER_API_AUTHBASIC (expected <login>:<password>)"
	fi
	htpasswd -bc $HTPASSWD "$AUTHUSER" "$AUTHPWD"
fi

# The API has no protection by itself: when OAuth2 clients are given, the
# LemonLDAP::NG OAuth2 handler accepts only access tokens issued to one of
# these clients by the client credentials grant (so not tied to a user)
echo "Generate $PSGI"
perl -e '
my $protection = "none";
my @clients = grep { length } split /[,\s]+/, $ENV{MANAGER_API_OAUTH2_CLIENTS};
if (@clients) {
	foreach (@clients) {
		die "Bad client ID in MANAGER_API_OAUTH2_CLIENTS: $_\n"
		  unless m{^[\w.:/-]+$};
	}
	$protection = q{$_oidc_grant_type eq "clientcredentials" and ($_clientId eq }
	  . join( q{ or $_clientId eq }, map { qq{"$_"} } @clients ) . ")";
	my $scope = $ENV{MANAGER_API_OAUTH2_SCOPE};
	if ( length $scope ) {
		die "Bad MANAGER_API_OAUTH2_SCOPE: $scope\n"
		  unless $scope =~ /^[\w.:\/-]+$/;
		$protection .= q{ and $_scope =~ /(?<!\S)} . quotemeta($scope) . q{(?!\S)/};
	}
	print STDERR "API access rule: $protection\n";
}
$protection =~ s/([\\\x27])/\\$1/g;
print "# Generated at startup from MANAGER_API* variables, do not edit\n",
  "use Lemonldap::NG::Manager;\n\n",
  "Lemonldap::NG::Manager->run(\n",
  "    { enabledModules => \x27api\x27, protection => \x27$protection\x27 } );\n";
' >$PSGI || die "unable to build $PSGI"

echo "Generate $CONF"
perl -e '
my %r;
use Socket qw(inet_pton AF_INET AF_INET6);
if ( length $ENV{MANAGER_API_ALLOW} ) {
	foreach ( grep { length } split /[,\s]+/, $ENV{MANAGER_API_ALLOW} ) {
		my ( $ip, $mask ) = m#^([^/]+)(?:/(\d{1,3}))?$#
		  or die "Bad MANAGER_API_ALLOW value: $_\n";
		my $max = inet_pton( AF_INET, $ip ) ? 32 : inet_pton( AF_INET6, $ip ) ? 128
		  : die "Bad MANAGER_API_ALLOW address: $_\n";
		die "Bad MANAGER_API_ALLOW mask: $_\n" if defined $mask and $mask > $max;
		die "MANAGER_API_ALLOW=$_ allows everybody, not accepted without another protection\n"
		  if defined $mask and $mask == 0
		  and !length $ENV{MANAGER_API_AUTHBASIC}
		  and $ENV{MANAGER_API_OAUTH2_CLIENTS} !~ /\S/;
		$r{ACCESS} .= "  allow $_;\n";
	}
	die "Empty MANAGER_API_ALLOW\n" unless $r{ACCESS};
	$r{ACCESS} .= "  deny all;\n";

	# Client address is read from FORWARDED_HEADER when the request comes
	# from FORWARDED_BY: trusting everybody makes the allow list spoofable
	if ( grep { m#/0$# } split /[,\s]+/, $ENV{FORWARDED_BY} ) {
		my $msg = "MANAGER_API_ALLOW can be bypassed since FORWARDED_BY "
		  . "trusts any client ($ENV{FORWARDED_BY}), set it to your reverse "
		  . "proxy addresses";
		die "$msg\n"
		  if !length $ENV{MANAGER_API_AUTHBASIC}
		  and $ENV{MANAGER_API_OAUTH2_CLIENTS} !~ /\S/;
		print STDERR "WARNING: $msg\n";
	}
}
if ( length $ENV{MANAGER_API_AUTHBASIC} ) {
	$r{ACCESS} .= "  auth_basic \"LLNG manager API\";\n"
	  . "  auth_basic_user_file /etc/lemonldap-ng/manager-api.htpasswd;\n";
}
$r{READONLY} = "    limit_except GET HEAD {\n      deny all;\n    }\n"
  if $ENV{MANAGER_API_READONLY} eq "yes";
$r{VHOSTTYPE} = "    fastcgi_param VHOSTTYPE OAuth2;\n"
  if $ENV{MANAGER_API_OAUTH2_CLIENTS} =~ /\S/;
while (<>) {
	s/^\s*#__(\w+)__\s*\n/$r{$1}/;
	print;
}
' $TEMPLATE >$CONF.new || die "unable to build $CONF"
mv $CONF.new $CONF

perl -i -pe 's#__FASTCGISOCKDIR__#/run/llng-fastcgi-server#g;
s#__PORT__#$ENV{LISTEN}#g;
s#__DNSDOMAIN__#$ENV{SSODOMAIN}#g;
' $CONF

if test "$NGINX_LOG_JSON" != ""; then
	perl -i -pe 's/access_log\s+(.*)\s+llng\s*;/access_log $1 llng_json;/' $CONF
fi

if test "$TLS_CERT_FILE"; then
	echo "Configure SSL into $CONF"
	perl -i -pe 'BEGIN{our $setCert="
  ssl_certificate $ENV{TLS_CERT_FILE};
  ssl_certificate_key $ENV{TLS_KEY_FILE};
"};s/^(\s*server_name)/$setCert$1/' $CONF
fi

setXforwardedForIfNeeded $CONF
