apiVersion: v1
entries:
  lemonldap:
  - apiVersion: v2
    appVersion: 2.21.5-1
    created: "2026-08-14T06:23:05.134396592Z"
    dependencies:
    - name: commons
      repository: file://charts/commons
      version: 1.0.0
    description: A Helm chart for LemonLDAP::NG (manager, portal and maintenance cronjob)
    digest: 9ebc004265bcacbe901b25eeca766d8102b68e5dadc672993a2cc5e60e65665b
    home: https://github.com/guimard/llng-docker
    icon: https://lemonldap-ng.org/images/llng_opengraph.png
    kubeVersion: '>=1.22'
    maintainers:
    - email: yadd@debian.org
      name: Xavier Guimard
      url: https://github.com/guimard
    name: lemonldap
    sources:
    - https://github.com/guimard/llng-docker
    - https://github.com/LemonLDAPNG/lemonldap-ng
    urls:
    - https://guimard.github.io/llng-docker/helm/lts-2.21/lemonldap-2.21.5.tgz
    version: 2.21.5
  - apiVersion: v2
    appVersion: 2.21.4-5
    created: "2026-08-14T06:23:05.133231808Z"
    dependencies:
    - name: commons
      repository: file://charts/commons
      version: 1.0.0
    description: A Helm chart for LemonLDAP::NG (manager, portal and maintenance cronjob)
    digest: 78cf0c9d699ce8f62ebc42d9d55619f9d3248f8d5c00d49291fcc02f7a27721d
    home: https://github.com/guimard/llng-docker
    icon: https://lemonldap-ng.org/images/llng_opengraph.png
    kubeVersion: '>=1.22'
    maintainers:
    - email: yadd@debian.org
      name: Xavier Guimard
      url: https://github.com/guimard
    name: lemonldap
    sources:
    - https://github.com/guimard/llng-docker
    - https://github.com/LemonLDAPNG/lemonldap-ng
    urls:
    - https://guimard.github.io/llng-docker/helm/lts-2.21/lemonldap-2.21.4.tgz
    version: 2.21.4
generated: "2026-08-14T06:23:05.131758837Z"
