#!/bin/sh

set -e

LIST=${LIST:-pg base portal manager full ssoaas-fastcgi-server dev}

for i in $LIST; do
	(
	cd $i
	if test "$i" = "dev"; then
		./build-dev
	else
		NAME=`grep 'name="yadd/' Dockerfile|sed -e 's/.*name="//' -e 's/".*$//'`
		docker build --rm -t $NAME .
		if test "$PUBLISH" = "yes"; then
			docker push $NAME
		fi
	fi
	)
done
