#!/bin/bash

set -e

LIST=${LIST:-pg base portal uwsgi-portal manager full ssoaas-fastcgi-server cron cron-task sessions-backup webpubsub}
#LIST=${LIST:-pg base portal uwsgi-portal manager full ssoaas-fastcgi-server cron dev}

if test "$(cd base && md5sum *.patch|sort)" != "$(cd base-no-s6 && md5sum *.patch|sort)"; then
	echo "Base patches differ" >&2
	exit 1
fi
if test "$(cd portal && md5sum *.patch|sort)" != "$(cd uwsgi-portal && md5sum *.patch|sort)"; then
	echo "Portal patches differ" >&2
	exit 1
fi
if test "$(cd manager && md5sum *.patch|sort)" != "$(cd full && md5sum *.patch|sort)"; then
	echo "Manager patches differ" >&2
	exit 1
fi
if test "`md5sum uwsgi-portal/install/etc/cont-init.d/update-nginx-portal-conf|sed -e 's/ .*$//'`" != "`md5sum portal/install/etc/cont-init.d/update-nginx-portal-conf|sed -e 's/ .*$//'`"; then
	echo "Portal install differ" >&2
	exit 1
fi

for i in $LIST; do
	(
	cd $i
	if test "$i" = "dev"; then
		./build-dev
	else
		NAME=`grep 'name="yadd/' Dockerfile|sed -e 's/.*name="//' -e 's/".*$//'`
		docker build --rm -t $NAME --build-arg="BASE=yadd/lemonldap-ng-base:latest" --build-arg "PORTALBASE=yadd/lemonldap-ng-portal:latest" .
		if test "$IMAGE_EXPORT" = "yes"; then
			docker save $NAME > /tmp/$i.tar
		fi
		if test "$PUBLISH" = "yes"; then
			docker push $NAME
		fi
	fi
	if test "$i" != "full"; then
		if test -x test; then
			./test
		fi
	fi
	)
done
for i in $LIST; do
	(
	cd $i
	if test -x clean; then
		./clean || true
	fi
	)
done
if test "$IMAGE_EXPORT" = "yes"; then
	(
	cd /tmp
	tar czf images.tar.gz ${LIST// /.tar }.tar
	)
fi
