{{- if and .Values.config.postgres.enabled .Values.config.postgres.initJob.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lemonldap.fullname" . }}-init-secrets-env
  labels:
    {{- include "lemonldap.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "10"  
type: Opaque
data:
  PG_USER: {{ .Values.config.postgres.username | b64enc | quote }}
  PG_PASSWORD: {{ .Values.config.postgres.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.config.postgres.admin.dbName | default "dummy" | b64enc | quote }}
  POSTGRES_USER: {{ .Values.config.postgres.admin.username | default "dummy" | b64enc | quote }}
  PGPASSWORD: {{ .Values.config.postgres.admin.password | default "dummy" | b64enc | quote }}
{{- end }}