{{- if .Values.config.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lemonldap.fullname" . }}-secrets-env
  labels:
    {{- include "lemonldap.labels" . | nindent 4 }}
type: Opaque
data:
  DBI_USER: {{ .Values.config.postgres.username | b64enc | quote }}
  DBI_PASSWORD: {{ .Values.config.postgres.password | b64enc | quote }}
{{- end }}