#!/bin/sh

set -e

DATE=`date +'%Y%m%d'`

VERSION=`curl -s -H 'Accept: application/json' https://gitlab.ow2.org/api/v4/projects/181/repository/tags| \
perl -MJSON -MDevscripts::Versort -lne '$a.=$_}{
	$a=JSON::from_json($a);
	@v = map {s/^v//;[$_]} map {$_->{name}} grep {$_->{name}=~/^v\d/} @$a;
	@v = Devscripts::Versort::upstream_versort(@v);
	$,="\n";
	print map {s/-1$//;$_->[0]} @v;
'|head -n1`

docker build --rm -t yadd/lemonldap-ng-dev:$VERSION-$DATE -t yadd/lemonldap-ng-dev:latest .

if test "$PUBLISH" = "yes"; then
	echo
	echo "docker push yadd/lemonldap-ng-dev:$VERSION-$DATE"
	docker push yadd/lemonldap-ng-dev:$VERSION-$DATE yadd/lemonldap-ng-dev:latest
else
	echo
	echo "Built. Next: docker push yadd/lemonldap-ng-dev:$VERSION-$DATE"
fi
