{{- if and .Values.manager.enabled .Values.config.manager.api.enabled .Values.config.manager.api.authBasic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lemonldap.fullname" . }}-manager-api
  labels:
    {{- include "lemonldap.labels" . | nindent 4 }}
type: Opaque
data:
  MANAGER_API_AUTHBASIC: {{ .Values.config.manager.api.authBasic | b64enc | quote }}
{{- end }}
