version: "3.4"

services:
  db:
    image: yadd/lemonldap-ng-pg-database
    environment:
      - POSTGRES_PASSWORD=zz
    healthcheck:
      test: "exit 0"

  redis:
    image: redis

  portal:
    image: yadd/lemonldap-ng-portal
    environment:
      - PG_SERVER=db
      - REDIS_SERVER=redis:6379
      - LOGGER=stderr
      - USERLOGGER=stderr
      - FORCE_KEY_REGENERATION=yes
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  authserver:
    image: yadd/lemonldap-ng-ssoaas-fastcgi-server
    environment:
      - PG_SERVER=db
      - REDIS_SERVER=redis:6379
      - LOGGER=stderr
      - USERLOGGER=stderr
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  nginxapp:
    image: yadd/nginx-protected-app
    environment:
      - AUTHSERVER=authserver:9001
      - PROTECTEDHOST=test.example.com
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      authserver:
        condition: service_started

  haproxy:
    image: haproxy:2.6-bullseye
    ports:
      - 80:80
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    depends_on:
      - portal
