apiVersion: v1
entries:
  lemonldap:
  - apiVersion: v2
    appVersion: 2.23.0-2
    created: "2026-07-01T11:42:17.086045276Z"
    dependencies:
    - name: commons
      repository: file://charts/commons
      version: 1.0.0
    description: A Helm chart for LemonLDAP::NG (manager, portal and maintenance cronjob)
    digest: 4515cbd64955cf1872346e23b4943ed623e82d20f0d2d35d23ecf1f2bfe2ced3
    home: https://github.com/guimard/llng-docker
    icon: https://lemonldap-ng.org/images/llng_opengraph.png
    kubeVersion: '>=1.22'
    maintainers:
    - email: yadd@debian.org
      name: Xavier Guimard
      url: https://github.com/guimard
    name: lemonldap
    sources:
    - https://github.com/guimard/llng-docker
    - https://github.com/LemonLDAPNG/lemonldap-ng
    urls:
    - https://guimard.github.io/llng-docker/helm/latest/lemonldap-2.23.0-2.tgz
    version: 2.23.0-2
generated: "2026-07-01T11:42:17.084550432Z"
