version: "3.4"

services:
  auth.example.com:
    container_name: test_portal_with_supertest
    image: yadd/lemonldap-ng-portal
    environment:
      - LOGGER=stderr
      - USERLOGGER=stderr
      - "RELAY=foo.example.com=http://auth.example.com/static/"
    networks:
      uportaltest:
        aliases:
          - foo.example.com
  test:
    image: yadd/lemonldap-ng-portal-test
    build:
      context: .
    depends_on:
      auth.example.com:
        condition: service_started
    networks:
      uportaltest:

networks:
  uportaltest:
    name: uportaltest
