#!/command/with-contenv sh

set -e

if test "$PROTECTION" != ""; then
  echo "Set manager protection to $PROTECTION"
  perl -i -pe 's/^protection\s*=.*$/protection='$PROTECTION'/' /etc/lemonldap-ng/lemonldap-ng.ini
fi

#if test "$RELAY" != ''; then
#	echo "Configure wanted relay(s)"
#	perl -e '
#use strict;
#my $res;
#my @list = split /\s*;\s*/, $ENV{RELAY};
#foreach(@list) {
#	die "Bad relay value $_" unless m#^(.*?)=(https?://.*/)$#;
#	print <<EOF
#server {
#  listen 80;
#  listen [::]:80;
#  server_name $1;
#  #set_real_ip_from  127.0.0.1;
#  #real_ip_header    X-Forwarded-For;
#  location / {
#    proxy_pass $2;
#    proxy_redirect off;
#    proxy_set_header Host \$host:\$server_port;
#    proxy_set_header X-Real-IP \$remote_addr;
#    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
#  }
#}
#EOF
#}
#' >/etc/nginx/sites-enabled/zzzz-relay.conf
#	FILES="$FILES /etc/nginx/sites-enabled/zzzz-relay.conf"
#
#fi

#setXforwardedForIfNeeded $FILES
