{{- if .Values.global.images.dockerCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-pull-secrets
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "common.dockerCredentials" . }}
{{- end }}