#!/bin/bash


for INITSCRIPT in /etc/cont-init.d/*; do
	sh $INITSCRIPT
done

if [ -z "$( ls '/etc/services.d/' )" ]; then
	echo "No services to run"
else
	for STARTDIR in /etc/services.d/*; do
		NAME=${STARTDIR##*/}
		echo "Starting service: $NAME"
		start-stop-daemon -C --background --oknodo --start --exec $STARTDIR/run
	done
fi

echo "ARGS $@"

"$@"
