#!/command/with-contenv sh

HOSTNAME=${PORTAL#*://}
HOSTNAME=${HOSTNAME%/*}
export HOSTNAME

perl -i -pe 's#__FASTCGISOCKDIR__#/run/llng-fastcgi-server#g;
s#__PORT__#80#g;
s#__SERVERNAME__#$ENV{HOSTNAME}#g;
s#__DNSDOMAIN__#$ENV{SSODOMAIN}#g;
s#__PORTALSITEDIR__#/usr/share/lemonldap-ng/portal/htdocs/#g;
s#__PORTALSTATICDIR__#/usr/share/lemonldap-ng/portal/htdocs/static/#g;
' /etc/lemonldap-ng/portal-nginx.conf
