#!/command/with-contenv sh

PORTAL=${PORTAL:-auth.example.com}
PORTALHOST=`portalHost "$PORTAL"`
SSODOMAIN=${SSODOMAIN:-example.com}
SERVERNAME=${SERVERNAME:-${PORTALHOST}}
SERVERNAME=${SERVERNAME%/*}
export SERVERNAME

perl -i -pe 's#__FASTCGISOCKDIR__#/run/llng-fastcgi-server#g;
s#__PORT__#80#g;
s#__SERVERNAME__#$ENV{SERVERNAME}#g;
s#__DNSDOMAIN__#$ENV{SSODOMAIN}#g;
s#__PORTALSITEDIR__#/usr/share/lemonldap-ng/portal/htdocs/#g;
s#__PORTALSTATICDIR__#/usr/share/lemonldap-ng/portal/htdocs/static/#g;
' /etc/lemonldap-ng/portal-nginx.conf

if test "$TLS_CERT_FILE"; then
	perl -i -pe 's/^(\s*listen.*)80/${1}443/' /etc/lemonldap-ng/portal-nginx.conf
	if grep ssl_certificate /etc/lemonldap-ng/portal-nginx.conf; then
		echo "SSL already configured ?"
	else
		perl -i -pe 'BEGIN{our $setCert="
  ssl_certificate $ENV{TLS_CERT_FILE};
  ssl_certificate_key $ENV{TLS_KEY_FILE};
"};s/^(\s*server_name)/$setCert$1/' /etc/lemonldap-ng/portal-nginx.conf
	fi
	cat /etc/lemonldap-ng/portal-nginx.conf
fi

if test "$RELAY" != ''; then
	set -e
	perl -e '
use strict;
my $res;
my @list = split /\s*;\s*/, $ENV{RELAY};
foreach(@list) {
	die "Bad relay value $_" unless m#^(.*?)=(https?://.*/)$#;
	print <<EOF
server {
  listen 80;
  listen [::]:80;
  server_name $1;
  location / {
    proxy_pass $2;
  }
}
EOF
}
' >/etc/nginx/sites-enabled/zzzz-relay.conf
fi
