#!/bin/sh

set -e

docker-compose run base cat /etc/lemonldap-ng/lemonldap-ng.ini | grep 'dbiChain=DBI:Pg:database=lemonldapng;host=db'
docker-compose run base /usr/share/docker-llng/updateConf get persistentStorage|grep Apache::Session::Browseable::PgJSON
docker-compose run base /usr/share/docker-llng/updateConf get globalStorage|grep Apache::Session::Browseable::Redis
docker-compose run base /usr/share/docker-llng/updateConf get domain|grep debian.org
docker-compose run base /usr/share/docker-llng/updateConf get authChoiceModules|grep 1_LDAP
docker-compose run base /usr/share/docker-llng/updateConf get applicationList 1sample catname|grep "applications"
docker-compose run base /usr/share/docker-llng/updateConf get exportedVars aa|grep bb
docker-compose down
