#!/bin/sh

if which docker-compose; then
	COMPOSE='docker-compose'
else
	COMPOSE='docker compose'
fi

set -e

$COMPOSE run base cat /etc/lemonldap-ng/lemonldap-ng.ini | grep 'dbiChain=DBI:Pg:database=lemonldapng;host=db'
$COMPOSE run base /usr/share/docker-llng/updateConf get persistentStorage | grep Apache::Session::Browseable::PgJSON
$COMPOSE run base /usr/share/docker-llng/updateConf get globalStorage | grep Apache::Session::Browseable::Redis
$COMPOSE run base /usr/share/docker-llng/updateConf get globalStorageOptions Index | grep _whatToTrace
$COMPOSE run base /usr/share/docker-llng/updateConf get domain | grep debian.org
$COMPOSE run base /usr/share/docker-llng/updateConf get authChoiceModules | grep 1_LDAP
$COMPOSE run base /usr/share/docker-llng/updateConf get applicationList 1sample catname | grep "Some applications"
$COMPOSE run base /usr/share/docker-llng/updateConf get exportedVars aa | grep bb
$COMPOSE run base /usr/share/docker-llng/updateConf get macros | grep ZZ
$COMPOSE run base /usr/share/docker-llng/updateConf get portal | grep dockertest.com
$COMPOSE run base grep languages /etc/lemonldap-ng/lemonldap-ng.ini | perl -pe 's/\r//g' | grep -E '^languages *= *en,fr$'
$COMPOSE down
