name: Common docker publish setup
description: common steps for docker-publish jobs
inputs:
  DOCKER_USERNAME:
    required: true
    description: Docker username
  DOCKER_PASSWORD:
    required: true
    description: Docker password
  DOCKER_IMAGE:
    required: true
    description: Image name
  DIRNAME:
    required: true
    description: Working directory
  IMAGE_SUFFIX:
    required: false
    description: Optional image suffix
  IMAGE_SUFFIX2:
    required: false
    description: Optional image suffix
  SHORT_DESCRIPTION:
    required: true
    description: Short description
  VERSION:
    required: valse
    default: no

runs:
  using: "composite"
  steps:
      - name: Get current date
        id: date
        shell: bash
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.DOCKER_USERNAME }}
          password: ${{ inputs.DOCKER_PASSWORD }}
      - name: Set main version
        id: setversion
        shell: bash
        run: |
          VERSION="${{ inputs.VERSION }}"
          if [[ "$VERSION" == "no" ]]; then
            VERSION="${{ env.VERSION }}-${{ env.DOCKERREVISION }}"
          fi
          echo "✅ Using VERSION: $VERSION"
          if [[ "$VERSION" == "no" ]]; then exit 1; fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Define platforms
        id: platforms
        shell: bash
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "platforms=linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x" >> $GITHUB_OUTPUT
          else
            echo "platforms=linux/amd64" >> $GITHUB_OUTPUT
          fi
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.DOCKER_IMAGE }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.DIRNAME }}
          build-args: |
            BASE=yadd/lemonldap-ng-base:latest${{ inputs.IMAGE_SUFFIX }}
            PORTALBASE=yadd/lemonldap-ng-portal:latest${{ inputs.IMAGE_SUFFIX }}
          platforms: ${{ steps.platforms.outputs.platforms }}
          push: true
          tags: |
            ${{ inputs.DOCKER_IMAGE }}:latest${{ inputs.IMAGE_SUFFIX }}
            ${{ inputs.DOCKER_IMAGE }}:${{ steps.date.outputs.date }}${{ inputs.IMAGE_SUFFIX }}${{ inputs.IMAGE_SUFFIX2 }}
            ${{ inputs.DOCKER_IMAGE }}:${{ steps.setversion.outputs.version }}${{ inputs.IMAGE_SUFFIX }}${{ inputs.IMAGE_SUFFIX2 }}
            ${{ inputs.DOCKER_IMAGE }}:${{ steps.setversion.outputs.version }}-${{ env.DEBIANRELEASE }}${{ inputs.IMAGE_SUFFIX }}${{ inputs.IMAGE_SUFFIX2 }}
      - name: push README to Dockerhub
        if: inputs.SHORT_DESCRIPTION != 'no'
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ inputs.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ inputs.DOCKER_PASSWORD }}
        with:
          destination_container_repo: ${{ inputs.DOCKER_IMAGE }}
          provider: dockerhub
          short_description: ${{ inputs.SHORT_DESCRIPTION }}
          readme_file: ${{ inputs.DIRNAME }}/README.md
