name: Build and test Docker Images

env:
  VERSION: 2.20.0
  PGVERSION: 15
  DEBIANRELEASE: bookworm
  DOCKERREVISION: 2

on:
  push:
    branches-ignore: [master,stable,experimental]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build_and_test
        run: ./build-all
        env:
          VERSION: ${{ env.VERSION }}-${{ env.DOCKERREVISION }}
