name: Build and test Docker Images

on:
  push:
    branches-ignore: [master,stable,experimental]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build_and_test
        run: ./build-all
